apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: sa-cluster-admin
subjects:
- kind: ServiceAccount
  name: playground # Name is case sensitive
  namespace: airflow
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: manage-pods
  apiGroup: rbac.authorization.k8s.io